import Link from "next/link";
import { DocH2 } from "@components/docs/DocHeading";
import { DocPage } from "@components/docs/DocPage";
import { DocTip } from "@components/docs/DocTip";

const tools = [
  {
    name: "snapshot",
    description: "Read the page accessibility tree and get stable element references.",
    when: "After every page load or major DOM mutation.",
  },
  {
    name: "highlight",
    description: "Draw a colored outline around a specific element reference.",
    when: "To visually confirm the correct target before clicking or typing.",
  },
  {
    name: "click",
    description: "Click an interactive element (button, link, toggle).",
    when: "Submitting forms or navigating through UI flows.",
  },
  {
    name: "fill",
    description: "Input text into a field or textarea.",
    when: "Logging in, searching, or completing forms.",
  },
  {
    name: "read_logs",
    description: "Extract the browser's console output (errors, warnings, logs).",
    when: "Verifying if a recent action caused a client-side exception.",
  },
  {
    name: "read_network",
    description: "Retrieve recent network requests (XHR/Fetch) in HAR format.",
    when: "Debugging failing API calls or monitoring payload data.",
  },
  {
    name: "screenshot",
    description: "Capture the full viewport or a specific element as a base64 image.",
    when: "Visual verification or sharing exact state with the user.",
  },
  {
    name: "pick_element",
    description: "Activate the visual picker in the browser.",
    when: "Requesting human-in-the-loop intervention for complex element selection.",
  },
  {
    name: "navigate",
    description: "Transition the browser to a new URL.",
    when: "Starting a new task or flow.",
  },
  {
    name: "eval",
    description: "Execute raw JavaScript within the active page context.",
    when: "For advanced edge cases not covered by standard tools.",
  },
];

const toc = [
  { id: "overview", title: "Overview", level: 2 as const },
  { id: "tools", title: "Tools Reference", level: 2 as const },
  { id: "workflow", title: "Optimal Workflow", level: 2 as const },
];

export default function McpToolsPage() {
  return (
    <DocPage
      title="Tools Reference"
      description="A comprehensive guide to the MCP tools exposed by the Grip Daemon, optimized for AI agent workflows."
      toc={toc}
    >
      <DocH2 id="overview">Overview</DocH2>
      <p>
        The Grip Daemon provides a standardized suite of MCP tools designed to let AI agents interact with web pages reliably. 
        These tools translate high-level requests into low-level Chrome DevTools Protocol commands.
      </p>
      <DocTip>
        <strong>Important:</strong> Element references generated by the <code>snapshot</code> tool are ephemeral. They expire upon navigation or significant DOM updates. Always request a fresh snapshot before interacting with a changed page.
      </DocTip>
      <p>
        If your AI tool is not yet connected to the daemon, refer to the <Link href="/docs/mcp/configuration">Configuration Guide</Link>.
      </p>

      <DocH2 id="tools">Tools Reference</DocH2>
      <div className="doc-tool-list">
        {tools.map((tool) => (
          <div key={tool.name} className="doc-tool-item">
            <code className="doc-tool-name">{tool.name}()</code>
            <p>{tool.description}</p>
            <p className="doc-tool-when">
              <strong>When to use:</strong> {tool.when}
            </p>
          </div>
        ))}
      </div>

      <DocH2 id="workflow">Optimal Workflow</DocH2>
      <p>For the highest reliability, AI agents should adhere to this interaction loop:</p>
      <ol>
        <li>
          <strong>Inspect</strong>: Call <code>snapshot()</code> to retrieve the current layout and available interactive elements.
        </li>
        <li>
          <strong>Verify</strong>: (Optional) Call <code>highlight(ref)</code> to ensure the intended target is correct.
        </li>
        <li>
          <strong>Act</strong>: Call <code>click(ref)</code> or <code>fill(ref, value)</code> to manipulate the page.
        </li>
        <li>
          <strong>Validate</strong>: Call <code>read_logs()</code> to verify no unexpected errors were triggered by the action.
        </li>
      </ol>
    </DocPage>
  );
}
