export { gripUserError } from "./errors";
export {
  ensureTabReady,
  injectGripScripts,
  pingTab,
  REFRESH_HINT,
  sendToTab,
  sendToTabWhenReady,
  waitForGrip,
} from "./tab-bridge";
export { isExtensionContextValid, safeSendMessage } from "./runtime";
export {
  bindChipTooltipRoot,
  bindTrayBadgeTooltips,
  hideChipTooltip,
  type ChipTooltipMeta,
  chipMetaFromElement,
  createChipElement,
  createDefaultChip,
  bindEditorClipboard,
  focusEditor,
  handleEditorKeydown,
  INLINE_CHIP_CLASS,
  INLINE_EDITOR_CLASS,
  insertChipAtSelection,
  isEditorEmpty,
  placeCaretAtEnd,
  removeChipElement,
  findChipElement,
  selectChipElement,
  serializeEditor,
  serializeSelectionForClipboard,
  setEditorFromComment,
  updateChipActiveStates,
  type InlineChipRef,
} from "@grip/devtools-lib";
